name: Coverage Reporter

on:
  # Triggers the workflow on push or pull request events
  push:
    branches:
    - main
    - developer

  # Runs this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  codacy-coverage-reporter:
    env:
      VCPKG_ROOT: /usr/local/share/vcpkg

    # The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: codacy-coverage-reporter,
            os: ubuntu-latest,
            preset_name: "clang-coverage",
            binary_dir: "out/build/clang-coverage"
          }

    steps:
      - name: Get Branch Name
        id: branch-name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Print Event
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          echo github.branch: ${{ steps.branch-name.outputs.branch }}

      - name: Install Dependencies
        run: |
          sudo apt-get install ninja-build
          sudo apt-get install lcov
          ninja    --version
          cmake    --version
          gcc      --version
          gcc-11   --version
          clang    --version
          clang-14 --version
          lcov     --version
          vcpkg    --version

      - name: Restore Build Cache
        id: restore-build-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            out/*
            build/*
            external/*
            test/external/*
            modules/infrastructure/external/*
          key: ${{ matrix.config.os }}-build-${{ matrix.config.preset_name }}-${{ hashFiles('CMakeLists.txt','test/CMakeLists.txt') }}
          restore-keys: |
            ${{ matrix.config.os }}-build-${{ matrix.config.preset_name }}

      - name: Clean Build Folder
        if: steps.restore-build-cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          rm -rf out
          rm -rf build
          mkdir build

      - name: Configure
        shell: bash
        run: |
          cmake --preset ${{ matrix.config.preset_name }}

      - name: Build
        shell: bash
        run: cmake --build --preset ${{ matrix.config.preset_name }} --target all

      - if: ${{ steps.branch-name.outputs.branch == 'developer' }}
        name: Save Build Cache
        id: save-build-cache
        uses: actions/cache/save@v4
        with:
          path: |
            out/*
            build/*
            external/*
            test/external/*
            modules/infrastructure/external/*
          key: ${{ matrix.config.os }}-build-${{ matrix.config.preset_name }}-${{ hashFiles('CMakeLists.txt','test/CMakeLists.txt') }}

      - name: Code Coverage Report
        shell: bash
        run: |
          HOME_DIRECTORY=$(pwd)
          cd ${{ matrix.config.binary_dir }}/bin
          ./improc_services_testd --gtest_output="xml:improc_services_tests.xml"
          cd "$HOME_DIRECTORY"
          cmake --build --preset ${{ matrix.config.preset_name }} --target improc_services_coverage

      - name: Unit Tests Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: "unit-tests-report"
          time_unit: milliseconds
          files: |
            **/improc_services_tests.xml

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./${{ matrix.config.binary_dir }}/improc_services_coverage.lcov
