name: CPP Build and Test

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: 
    - main
    - developer
  pull_request:
    branches: 
    - main

  # Runs this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "ubuntu-latest-gcc-boost-off",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc-11",
            cxx: "g++-11",
            generator: "Unix Makefiles",
            boost: "OFF",
            coverage: "OFF"
          }
        - {
            name: "ubuntu-latest-clang-boost-off",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "clang-14",
            cxx: "clang++-14",
            generator: "Unix Makefiles",
            boost: "OFF",
            coverage: "OFF"
          }
        - {
            name: "windows-latest-gcc-boost-off",
            os: windows-latest,
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            generator: "Ninja",
            boost: "OFF",
            coverage: "OFF"
          }
        - {
            name: "windows-latest-clang-boost-off",
            os: windows-latest,
            build_type: "Release",
            cc: "clang",
            cxx: "clang++",
            generator: "Ninja",
            boost: "OFF",
            coverage: "OFF"
          }
          
    steps:
      - name: Get Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v6
        
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Print Event
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          
      - name: Install Dependencies Linux
        if: startsWith(matrix.config.name, 'ubuntu-latest')
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build
          sudo apt-get install cmake
          sudo apt-get install gcc-11 g++-11
          sudo apt-get install clang-14
          sudo apt-get install lcov
          ninja    --version
          cmake    --version
          gcc      --version
          gcc-11   --version
          clang-14 --version
          lcov     --version
          git clone --recurse-submodules -b ${{ steps.branch-name.outputs.current_branch }} https://github.com/pirlruc/infrastructure.git modules/infrastructure

      - name: Install Dependencies Windows
        if: startsWith(matrix.config.name, 'windows-latest')
        run: |
          choco install ninja
          ninja    --version
          cmake    --version
          gcc      --version
          clang    --version
          git clone --recurse-submodules -b ${{ steps.branch-name.outputs.current_branch }} https://github.com/pirlruc/infrastructure.git modules/infrastructure
          
      - name: Restore Build Cache
        if: ${{ steps.branch-name.outputs.current_branch }} == 'developer'
        id: restore-build-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            build/*
            external/*
            test/external/*
            modules/infrastructure/external/*
          key: ${{ matrix.config.os }}-build-${{ matrix.config.cxx }}-${{ matrix.config.build_type }}-boost_${{ matrix.config.boost }}-coverage_${{ matrix.config.coverage }}-tests_ON-${{ hashFiles('CMakeLists.txt','test/CMakeLists.txt') }}
          restore-keys: |
            ${{ matrix.config.os }}-build-${{ matrix.config.cxx }}-${{ matrix.config.build_type }}-boost_${{ matrix.config.boost }}-coverage_${{ matrix.config.coverage }}-tests_ON-

      - name: Clean Build Folder
        if: steps.restore-build-cache.outputs.cache-hit != 'true' || ${{ steps.branch-name.outputs.current_branch }} != 'developer'
        shell: bash
        run: |
          rm -rf build
          mkdir build

      - name: Configure
        shell: bash
        run: |
          cmake \
            -S . \
            -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            -DCMAKE_INSTALL_PREFIX:PATH=install \
            -DIMPROC_WITH_BOOST=${{ matrix.config.boost }} \
            -DIMPROC_WITH_COVERAGE=${{ matrix.config.coverage }} \
            -DIMPROC_SERVICES_WITH_TESTS=ON \
            -G "${{ matrix.config.generator }}"
      
      - name: Build
        shell: bash
        run: cmake --build build --config ${{ matrix.config.build_type }} --target all

      - name: Save Build Cache
        if: ${{ steps.branch-name.outputs.current_branch }} == 'developer'
        id: save-build-cache
        uses: actions/cache/save@v3
        with:
          path: |
            build/*
            external/*
            test/external/*
            modules/infrastructure/external/*
          key: ${{ matrix.config.os }}-build-${{ matrix.config.cxx }}-${{ matrix.config.build_type }}-boost_${{ matrix.config.boost }}-coverage_${{ matrix.config.coverage }}-tests_ON-${{ hashFiles('CMakeLists.txt','test/CMakeLists.txt') }}

      - name: Test
        if: startsWith(matrix.config.coverage, 'OFF')
        shell: bash
        run: ./build/bin/improc_services_test
